language: csharp
mono: none
dotnet: 3.1.4

solution: MyProject.sln

install:
- dotnet restore
script:
- dotnet build
- dotnet test WebApi.Tests/WebApi.Tests.csproj
- dotnet test Domain.Tests/Domain.Tests.csproj
